# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
  - 0.5
notifications:
  email: false
# uncomment the following lines to override the default test script
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("FeigenbaumUtil"); Pkg.test("FeigenbaumUtil"; coverage=true)'
after_success:
  - julia -e julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("FeigenbaumUtil")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("FeigenbaumUtil")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("FeigenbaumUtil")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
sudo: required
